### ISSUE TITLE
 Element div not allowed as child of element ul 

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template#138]
The accordion list component has malformed HTML. HTML5 Validator shows this error: **"Element div not allowed as child of element ul**" This may or may not contribute to issue #137 (Accessibility of Accordion Lists) To correct this, the content div would need to be a child of the li, and a sibling to the anchor tag. 

As an alternative to the current solution developers can use the [Toggle component](https://beta.template.webtools.ca.gov/sample/toggle.html) to achieve the same functionality. Perhaps the theme should do the same to avoid duplicate functionality and code bloat.

**Comment by kkoryaka** [comment]
@markaplet, thank you for your feedbacks. and for bringing up great points. Recently, we have switched our template to Bootstrap 5 and jQuery-less approach, which means codebase for most of our components are now updated. Take a look again at our updated accordion list and see if your issue is still relevant. Our engineers are also taking thorough look at it to see if there are any potential accessibility issues.

**Comment by kkoryaka** [comment]
Our engineers checked the component and it's structure and they think that its structure looks good. Also, they have checked accessibility using NVDA and found that that opening an accordion heading and pressing down arrow reads the content. Let me know if your findings are different.

**Comment by markaplet** [comment]
The component has been replaced / updated since the issue was reported ~10 months ago. For anyone using the old ~v5.5 template and looking to certify, the offending line is here: https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/ae66630c8a045df890eeafc6f71f3e92c852d89f/sample/modules/accordion-list.html#L5
